/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DamageRouteImport } from './routes/damage'
import { Route as FlythroughRouteImport } from './routes/flythrough'
import { Route as HazardsRouteImport } from './routes/hazards'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TerrainRouteImport } from './routes/terrain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageRoute = DamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => rootRouteImport,
} as any)
const FlythroughRoute = FlythroughRouteImport.update({
  id: '/flythrough',
  path: '/flythrough',
  getParentRoute: () => rootRouteImport,
} as any)
const HazardsRoute = HazardsRouteImport.update({
  id: '/hazards',
  path: '/hazards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TerrainRoute = TerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/copilot': typeof CopilotRoute
  '/damage': typeof DamageRoute
  '/flythrough': typeof FlythroughRoute
  '/hazards': typeof HazardsRoute
  '/reports': typeof ReportsRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/copilot': typeof CopilotRoute
  '/damage': typeof DamageRoute
  '/flythrough': typeof FlythroughRoute
  '/hazards': typeof HazardsRoute
  '/reports': typeof ReportsRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/copilot': typeof CopilotRoute
  '/damage': typeof DamageRoute
  '/flythrough': typeof FlythroughRoute
  '/hazards': typeof HazardsRoute
  '/reports': typeof ReportsRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/copilot'
    | '/damage'
    | '/flythrough'
    | '/hazards'
    | '/reports'
    | '/terrain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/copilot'
    | '/damage'
    | '/flythrough'
    | '/hazards'
    | '/reports'
    | '/terrain'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/copilot'
    | '/damage'
    | '/flythrough'
    | '/hazards'
    | '/reports'
    | '/terrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CopilotRoute: typeof CopilotRoute
  DamageRoute: typeof DamageRoute
  FlythroughRoute: typeof FlythroughRoute
  HazardsRoute: typeof HazardsRoute
  ReportsRoute: typeof ReportsRoute
  TerrainRoute: typeof TerrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage': {
      id: '/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof DamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flythrough': {
      id: '/flythrough'
      path: '/flythrough'
      fullPath: '/flythrough'
      preLoaderRoute: typeof FlythroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazards': {
      id: '/hazards'
      path: '/hazards'
      fullPath: '/hazards'
      preLoaderRoute: typeof HazardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terrain': {
      id: '/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof TerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CopilotRoute: CopilotRoute,
  DamageRoute: DamageRoute,
  FlythroughRoute: FlythroughRoute,
  HazardsRoute: HazardsRoute,
  ReportsRoute: ReportsRoute,
  TerrainRoute: TerrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
